<?php

return [
    'stations' => [
        'Uttara North',
        'Uttara Center',
        'Uttara South',
        'Pallabi',
        'Mirpur 11',
        'Mirpur 10',
        'Kazipara',
        'Shewrapara',
        'Agargaon',
        'Bijoy Sarani',
        'Farmgate',
        'Karwan Bazar',
        'Shahbagh',
        'Dhaka University',
        'Bangladesh Secretariat',
        'Motijheel',
        'Kamlapur',
    ],

    'fares' => [
        'Uttara North' => [
            'Uttara North' => 00,
            'Uttara Center' => 20,
            'Uttara South' => 20,
            'Pallabi' => 30,
            'Mirpur 11' => 30,
            'Mirpur 10' => 40,
            'Kazipara' => 40,
            'Shewrapara' => 50,
            'Agargaon' => 60,
            'Bijoy Sarani' => 60,
            'Farmgate' => 70,
            'Karwan Bazar' => 80,
            'Shahbagh' => 80,
            'Dhaka University' => 90,
            'Bangladesh Secretariat' => 90,
            'Motijheel' => 100,
            'Kamlapur' => 100,

        ],
        'Uttara Center' => [
            'Uttara North' => 20,
            'Uttara Center' => 00,
            'Uttara South' => 20,
            'Pallabi' => 20,
            'Mirpur 11' => 30,
            'Mirpur 10' => 30,
            'Kazipara' => 40,
            'Shewrapara' => 40,
            'Agargaon' => 50,
            'Bijoy Sarani' => 60,
            'Farmgate' => 60,
            'Karwan Bazar' => 70,
            'Shahbagh' => 80,
            'Dhaka University' => 80,
            'Bangladesh Secretariat' => 90,
            'Motijheel' => 90,
            'Kamlapur' => 100,

        ],
        'Uttara South' => [
            'Uttara North' => 20,
            'Uttara Center' => 20,
            'Uttara South' => 00,
            'Pallabi' => 20,
            'Mirpur 11' => 20,
            'Mirpur 10' => 30,
            'Kazipara' => 30,
            'Shewrapara' => 40,
            'Agargaon' => 40,
            'Bijoy Sarani' => 50,
            'Farmgate' => 60,
            'Karwan Bazar' => 60,
            'Shahbagh' => 70,
            'Dhaka University' => 70,
            'Bangladesh Secretariat' => 80,
            'Motijheel' => 90,
            'Kamlapur' => 90,

        ],
        'Pallabi' => [
            'Uttara North' => 30,
            'Uttara Center' => 20,
            'Uttara South' => 20,
            'Pallabi' => 00,
            'Mirpur 11' => 20,
            'Mirpur 10' => 20,
            'Kazipara' => 20,
            'Shewrapara' => 30,
            'Agargaon' => 30,
            'Bijoy Sarani' => 40,
            'Farmgate' => 50,
            'Karwan Bazar' => 50,
            'Shahbagh' => 60,
            'Dhaka University' => 60,
            'Bangladesh Secretariat' => 70,
            'Motijheel' => 80,
            'Kamlapur' => 80,

        ],
        'Mirpur 11' => [
            'Uttara North' => 30,
            'Uttara Center' => 30,
            'Uttara South' => 20,
            'Pallabi' => 20,
            'Mirpur 11' => 00,
            'Mirpur 10' => 20,
            'Kazipara' => 20,
            'Shewrapara' => 20,
            'Agargaon' => 30,
            'Bijoy Sarani' => 40,
            'Farmgate' => 40,
            'Karwan Bazar' => 50,
            'Shahbagh' => 50,
            'Dhaka University' => 60,
            'Bangladesh Secretariat' => 70,
            'Motijheel' => 70,
            'Kamlapur' => 80,

        ],
        'Mirpur 10' => [
            'Uttara North' => 40,
            'Uttara Center' => 30,
            'Uttara South' => 30,
            'Pallabi' => 20,
            'Mirpur 11' => 20,
            'Mirpur 10' => 00,
            'Kazipara' => 20,
            'Shewrapara' => 20,
            'Agargaon' => 20,
            'Bijoy Sarani' => 30,
            'Farmgate' => 30,
            'Karwan Bazar' => 40,
            'Shahbagh' => 50,
            'Dhaka University' => 50,
            'Bangladesh Secretariat' => 60,
            'Motijheel' => 60,
            'Kamlapur' => 70,

        ],
        'Kazipara' => [
            'Uttara North' => 40,
            'Uttara Center' => 40,
            'Uttara South' => 30,
            'Pallabi' => 20,
            'Mirpur 11' => 20,
            'Mirpur 10' => 20,
            'Kazipara' => 00,
            'Shewrapara' => 20,
            'Agargaon' => 20,
            'Bijoy Sarani' => 20,
            'Farmgate' => 30,
            'Karwan Bazar' => 40,
            'Shahbagh' => 40,
            'Dhaka University' => 50,
            'Bangladesh Secretariat' => 50,
            'Motijheel' => 60,
            'Kamlapur' => 70,

        ],
         'Shewrapara' => [
            'Uttara North' => 50,
            'Uttara Center' => 40,
            'Uttara South' => 40,
            'Pallabi' => 30,
            'Mirpur 11' => 20,
            'Mirpur 10' => 20,
            'Kazipara' => 20,
            'Shewrapara' => 00,
            'Agargaon' => 20,
            'Bijoy Sarani' => 20,
            'Farmgate' => 20,
            'Karwan Bazar' => 30,
            'Shahbagh' => 80,
            'Dhaka University' => 80,
            'Bangladesh Secretariat' => 50,
            'Motijheel' => 50,
            'Kamlapur' => 60,

        ],
         'Agargaon' => [
            'Uttara North' => 60,
            'Uttara Center' => 50,
            'Uttara South' => 40,
            'Pallabi' => 30,
            'Mirpur 11' => 30,
            'Mirpur 10' => 20,
            'Kazipara' => 20,
            'Shewrapara' => 20,
            'Agargaon' => 00,
            'Bijoy Sarani' => 20,
            'Farmgate' => 20,
            'Karwan Bazar' => 20,
            'Shahbagh' => 30,
            'Dhaka University' => 30,
            'Bangladesh Secretariat' => 40,
            'Motijheel' => 50,
            'Kamlapur' => 50,

        ],
         'Bijoy Sarani' => [
            'Uttara North' => 60,
            'Uttara Center' => 60,
            'Uttara South' => 50,
            'Pallabi' => 40,
            'Mirpur 11' => 40,
            'Mirpur 10' => 30,
            'Kazipara' => 20,
            'Shewrapara' => 20,
            'Agargaon' => 20,
            'Bijoy Sarani' => 00,
            'Farmgate' => 20,
            'Karwan Bazar' => 20,
            'Shahbagh' => 20,
            'Dhaka University' => 30,
            'Bangladesh Secretariat' => 40,
            'Motijheel' => 40,
            'Kamlapur' => 50,

        ],
         'Farmgate' => [
            'Uttara North' => 70,
            'Uttara Center' => 60,
            'Uttara South' => 60,
            'Pallabi' => 50,
            'Mirpur 11' => 40,
            'Mirpur 10' => 30,
            'Kazipara' => 30,
            'Shewrapara' => 20,
            'Agargaon' => 20,
            'Bijoy Sarani' => 20,
            'Farmgate' => 00,
            'Karwan Bazar' => 20,
            'Shahbagh' => 20,
            'Dhaka University' => 20,
            'Bangladesh Secretariat' => 30,
            'Motijheel' => 30,
            'Kamlapur' => 40,

        ],
         'Karwan Bazar' => [
            'Uttara North' => 80,
            'Uttara Center' => 70,
            'Uttara South' => 60,
            'Pallabi' => 50,
            'Mirpur 11' => 50,
            'Mirpur 10' => 40,
            'Kazipara' => 40,
            'Shewrapara' => 30,
            'Agargaon' => 20,
            'Bijoy Sarani' => 20,
            'Farmgate' => 20,
            'Karwan Bazar' => 00,
            'Shahbagh' => 20,
            'Dhaka University' => 20,
            'Bangladesh Secretariat' => 20,
            'Motijheel' => 30,
            'Kamlapur' => 30,

        ],
         'Shahbagh' => [
            'Uttara North' => 80,
            'Uttara Center' => 80,
            'Uttara South' => 70,
            'Pallabi' => 60,
            'Mirpur 11' => 60,
            'Mirpur 10' => 50,
            'Kazipara' => 40,
            'Shewrapara' => 40,
            'Agargaon' => 30,
            'Bijoy Sarani' => 20,
            'Farmgate' => 20,
            'Karwan Bazar' => 20,
            'Shahbagh' => 00,
            'Dhaka University' => 20,
            'Bangladesh Secretariat' => 20,
            'Motijheel' => 20,
            'Kamlapur' => 30,

        ],
         'Dhaka University' => [
            'Uttara North' => 90,
            'Uttara Center' => 80,
            'Uttara South' => 70,
            'Pallabi' => 60,
            'Mirpur 11' => 60,
            'Mirpur 10' => 50,
            'Kazipara' => 50,
            'Shewrapara' => 40,
            'Agargaon' => 30,
            'Bijoy Sarani' => 30,
            'Farmgate' => 20,
            'Karwan Bazar' => 20,
            'Shahbagh' => 20,
            'Dhaka University' => 00,
            'Bangladesh Secretariat' => 20,
            'Motijheel' => 20,
            'Kamlapur' => 20,

        ],
         'Bangladesh Secretariat' => [
            'Uttara North' => 90,
            'Uttara Center' => 90,
            'Uttara South' => 80,
            'Pallabi' => 70,
            'Mirpur 11' => 70,
            'Mirpur 10' => 60,
            'Kazipara' => 50,
            'Shewrapara' => 50,
            'Agargaon' => 40,
            'Bijoy Sarani' => 40,
            'Farmgate' => 30,
            'Karwan Bazar' => 20,
            'Shahbagh' => 20,
            'Dhaka University' => 20,
            'Bangladesh Secretariat' => 00,
            'Motijheel' => 20,
            'Kamlapur' => 20,

        ],
         'Motijheel' => [
            'Uttara North' => 100,
            'Uttara Center' => 90,
            'Uttara South' => 90,
            'Pallabi' => 80,
            'Mirpur 11' => 70,
            'Mirpur 10' => 60,
            'Kazipara' => 60,
            'Shewrapara' => 50,
            'Agargaon' => 50,
            'Bijoy Sarani' => 40,
            'Farmgate' => 30,
            'Karwan Bazar' => 30,
            'Shahbagh' => 20,
            'Dhaka University' => 20,
            'Bangladesh Secretariat' => 20,
            'Motijheel' => 00,
            'Kamlapur' => 20,

        ],
         'Kamlapur' => [
           'Uttara North' => 100,
            'Uttara Center' => 100,
            'Uttara South' => 90,
            'Pallabi' => 80,
            'Mirpur 11' => 80,
            'Mirpur 10' => 70,
            'Kazipara' => 70,
            'Shewrapara' => 60,
            'Agargaon' => 50,
            'Bijoy Sarani' => 50,
            'Farmgate' => 40,
            'Karwan Bazar' => 30,
            'Shahbagh' => 30,
            'Dhaka University' => 20,
            'Bangladesh Secretariat' => 20,
            'Motijheel' => 20,
            'Kamlapur' => 00,
        ],
    ]

];
